This is my python notes

In [4]:
#importing pandas

#Ctrl + / for commenting
import pandas as pd

In [7]:
#Creating dataframe . Reading csv file using read_csv method
df=pd.read_csv("Data\survey_results_public.csv")
schema_df=pd.read_csv("C:\Users\SHETTS60\Documents\Python scripts\Data\survey_results_schema.csv")

In [8]:
#Gives count of rows,columns. Shape is an attribute hence "()" is not used
df.shape

(64461, 61)

In [9]:
#Gives count of rows,columns and datatype. Info is a method hence "()" is  used
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64461 entries, 0 to 64460
Data columns (total 61 columns):
Respondent                      64461 non-null int64
MainBranch                      64162 non-null object
Hobbyist                        64416 non-null object
Age                             45446 non-null float64
Age1stCode                      57900 non-null object
CompFreq                        40069 non-null object
CompTotal                       34826 non-null float64
ConvertedComp                   34756 non-null float64
Country                         64072 non-null object
CurrencyDesc                    45472 non-null object
CurrencySymbol                  45472 non-null object
DatabaseDesireNextYear          44070 non-null object
DatabaseWorkedWith              49537 non-null object
DevType                         49370 non-null object
EdLevel                         57431 non-null object
Employment                      63854 non-null object
Ethnicity                       45948 non-null object
Gender                          50557 non-null object
JobFactors                      49349 non-null object
JobSat                          45194 non-null object
JobSeek                         51727 non-null object
LanguageDesireNextYear          54113 non-null object
LanguageWorkedWith              57378 non-null object
MiscTechDesireNextYear          42379 non-null object
MiscTechWorkedWith              40314 non-null object
NEWCollabToolsDesireNextYear    47287 non-null object
NEWCollabToolsWorkedWith        52883 non-null object
NEWDevOps                       42686 non-null object
NEWDevOpsImpt                   41732 non-null object
NEWEdImpt                       48465 non-null object
NEWJobHunt                      42286 non-null object
NEWJobHuntResearch              41022 non-null object
NEWLearn                        56156 non-null object
NEWOffTopic                     50804 non-null object
NEWOnboardGood                  42623 non-null object
NEWOtherComms                   57205 non-null object
NEWOvertime                     43231 non-null object
NEWPurchaseResearch             37321 non-null object
NEWPurpleLink                   54803 non-null object
NEWSOSites                      58275 non-null object
NEWStuck                        54983 non-null object
OpSys                           56228 non-null object
OrgSize                         44334 non-null object
PlatformDesireNextYear          50605 non-null object
PlatformWorkedWith              53843 non-null object
PurchaseWhat                    39364 non-null object
Sexuality                       43992 non-null object
SOAccount                       56805 non-null object
SOComm                          56476 non-null object
SOPartFreq                      46792 non-null object
SOVisitFreq                     56970 non-null object
SurveyEase                      51802 non-null object
SurveyLength                    51701 non-null object
Trans                           49345 non-null object
UndergradMajor                  50995 non-null object
WebframeDesireNextYear          40024 non-null object
WebframeWorkedWith              42279 non-null object
WelcomeChange                   52683 non-null object
WorkWeekHrs                     41151 non-null float64
YearsCode                       57684 non-null object
YearsCodePro                    46349 non-null object
dtypes: float64(4), int64(1), object(56)
memory usage: 30.0+ MB

In [8]:
#set the max columns to display . To set rows, just replace columns with row in the below code
pd.set_option("display.max_columns",85)
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [11]:
# head method is used to display first values.By deafult its 5. You can gives no of rows to be printed inside "()"
df.head(2)

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4

In [16]:
# tail method is used to display last values.By deafult its 5. You can gives no of rows to be printed inside "()"
df.tail(2)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [6]:
#Creating Dummy dictionary. Creating list in dictionary
Details = { 
    'Name' : ['shishirshetty','Shir','Shir'],
    'Email' : ['shishirshetty@gmail.com','Shir@gmail.com','Shetty@gmail.com'],
    'Phone':[100,101,102]
}
#Assigning Dictionary to new Df
import pandas as pd
newdf = pd.DataFrame(Details)

In [23]:
#printing only 'name' column of newdf . You can use do it 2 ways
newdf['Name']
#or
newdf.Name

0    shishirshetty
1             Shir
2             Shir
Name: Name, dtype: object

In [5]:
#printing  'name', 'Email' column of newdf  together. 
#If we want to print more than one row or more than one column together make use of list ie. []
newdf[['Name','Email']]

NameError: name 'newdf' is not defined

In [3]:
#Get all the column names
newdf.columns

Index(['Email', 'Name', 'Phone'], dtype='object')

In [4]:
#'iloc' is used to access the particular by giving the Index of the row inside '[]'. iloc stands for index location
newdf.iloc[0]

Email    shishirshetty@gmail.com
Name               shishirshetty
Phone                        100
Name: 0, dtype: object

In [5]:
#printing 2 rows together
newdf.iloc[[0,1]]

                     Email           Name  Phone
0  shishirshetty@gmail.com  shishirshetty    100
1           Shir@gmail.com           Shir    101

In [13]:
#we can print the specified rows and columns using their indexes. [[0,1],1], where[0,1] is the row index and 1 is the column index
newdf.iloc[[0,1],1]

0    shishirshetty
1             Shir
Name: Name, dtype: object

In [10]:
#In 'iloc' we use index to print rows and columns, but in 'loc' we used index for rows and labels for columns.
#we can print the specified rows and columns using their indexes. [[0,1],'Email'], where[0,1] is the row index and 'Email' is the column label
newdf.loc[[0,1],'Email']

0    shishirshetty@gmail.com
1             Shir@gmail.com
Name: Email, dtype: object

In [11]:
#printing 2 rows and 2 columns together.[0,1] is the row index.['Name','Email'] is the column label
newdf.loc[[0,1],['Name','Email']]

            Name                    Email
0  shishirshetty  shishirshetty@gmail.com
1           Shir           Shir@gmail.com

In [19]:
#printing 2 rows together by using list slicer i.e,0:1. when you use slicer dont make us of '[]'
newdf.loc[0:1,['Name']]

            Name                    Email  Phone
0  shishirshetty  shishirshetty@gmail.com    100
1           Shir           Shir@gmail.com    101

In [19]:
#printing 2 columns together by using list slicer i.e, 'Name':'Phone'. when you use slicer dont make us of '[]'
newdf.loc[0:1,'Name':'Phone']

            Name  Phone
0  shishirshetty    100
1           Shir    101

In [15]:
#Setting index as 'Phone'.this wont permanently set it.
newdf.set_index("Phone")

                         Email           Name
Phone
100    shishirshetty@gmail.com  shishirshetty
101             Shir@gmail.com           Shir
102           Shetty@gmail.com           Shir

In [28]:
#Setting index as 'Phone'.this will permanently set it by using 'inplace'.
newdf.set_index("Phone", inplace=True)
newdf
#After setting index permanently we can no longer access using index in 'loc'. to access using index we have to use 'iloc'
#Always first analyse the data and identify the column that can be set as index

                Name                    Email
Phone
100    shishirshetty  shishirshetty@gmail.com
101             Shir           Shir@gmail.com
102           Shetty         Shetty@gmail.com

In [29]:
#'reset_index' is used to reset the index to default
newdf.reset_index(inplace=True)
newdf

   Phone           Name                    Email
0    100  shishirshetty  shishirshetty@gmail.com
1    101           Shir           Shir@gmail.com
2    102         Shetty         Shetty@gmail.com

In [61]:
#setting the 'column' as index.
schema_df.set_index('Column',inplace=True)
#Accessing one of the value(row) of Index column using loc
schema_df.loc['Hobbyist']

index                                 2
QuestionText    Do you code as a hobby?
Name: Hobbyist, dtype: object

In [69]:
#sort the index in ascending order. for descending order make 'ascending = false'
schema_df.sort_index(ascending=True)

               index                                       QuestionText
Column
Age               77  What is your age (in years)? If you prefer not...
Age1stCode        14  At what age did you write your first line of c...
BetterLife        58  Do you think people born today will have a bet...
BlockchainIs      57  Blockchain / cryptocurrency technology is prim...
BlockchainOrg     56  How is your organization thinking about or imp...
...              ...                                                ...
WorkPlan          33            How structured or planned is your work?
WorkRemote        35                    How often do you work remotely?
WorkWeekHrs       32   On average, how many hours per week do you work?
YearsCode         13  Including any education, how many years have y...
YearsCodePro      15  How many years have you coded professionally (...

[85 rows x 2 columns]

In [21]:
#Filtering. First assign the filter condition to one of the variale('filt') and then print it
filt = (newdf['Name']=='Shir')
newdf[filt]
#Also can pass the filter variable to 'loc' to get the particular column.Below code give result with only 'Phone' Column.
newdf.loc[filt,'Phone']

1    101
2    102
Name: Phone, dtype: int64

In [13]:
#AND operator '&'
filt = (newdf['Name']=='Shir') & (newdf['Phone']==101)
newdf.loc[filt,'Email']

#OR operator  '|'
filt = (newdf['Name']=='Shir') | (newdf['Phone']==101)
newdf.loc[filt,'Email']

#NOT operator '`'
filt = (newdf['Name']=='Shir')
newdf.loc[~filt,'Phone']

1      Shir@gmail.com
2    Shetty@gmail.com
Name: Email, dtype: object

In [26]:
#'isin' method is used like 'is present in the'. Create list of countries 'countries' and then apply filter for the dataframe using 'isin'
countries = ['United States','India','United Kingdom']
filt = (df['Country'].isin(countries))
df.loc[filt,'Country']

0        United Kingdom
3         United States
7                 India
9                 India
12        United States
              ...
88854    United Kingdom
88859     United States
88863    United Kingdom
88864             India
88877     United States
Name: Country, Length: 35747, dtype: object

In [34]:
#'str.contains' is one of the string method.'Python' is the string we are matching and 'na' Should be given as false since there might be no values sometime.
filt = (df['LanguageWorkedWith'].str.contains('Python',na= False))
df.loc[filt,['Country','LanguageWorkedWith']]

,Country,LanguageWorkedWith
0,United Kingdom,HTML/CSS;Java;JavaScript;Python
1,Bosnia and Herzegovina,C++;HTML/CSS;Python
3,United States,C;C++;C#;Python;SQL
4,Ukraine,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
7,India,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
...,...,...
88854,United Kingdom,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
88860,Brazil,Bash/Shell/PowerShell;C++;Python;Ruby;Other(s):
88865,Switzerland,Bash/Shell/PowerShell;HTML/CSS;Python;Other(s):
88872,Czech Republic,C;C++;HTML/CSS;JavaScript;PHP;Python;SQL
88876,Spain,HTML/CSS;JavaScript;Python

In [12]:
#to convert all the columns to Upper case
newdf.columns = (x.upper() for x in newdf.columns)
#to convert all the columns to lower case
newdf.columns = (x.lower() for x in newdf.columns)

In [17]:
#'replace' is used to rename columns,remove space etc.
newdf.columns = newdf.columns.str.replace('phoNe','Phone')

In [10]:
#Rename can also done by below method
newdf.rename(columns = {'Name':'NaMe'},inplace = True)

In [10]:
#to change Values of particular column of particular row can be done by below method
newdf.loc[[2],['Name','Phone']]=['Shishir',103]
newdf

            Name                    Email  Phone
0  shishirshetty  shishirshetty@gmail.com    100
1           Shir           Shir@gmail.com    101
2        Shishir         Shetty@gmail.com    103

In [18]:
#convert values in the 'Email' column to lower case. To convert into upper case replace 'lower' with 'upper'
newdf['Email'] = newdf['Email'].str.lower()
newdf

            Name                    Email  Phone
0  shishirshetty  SHISHIRSHETTY@GMAIL.COM    100
1           Shir           SHIR@GMAIL.COM    101
2        Shishir         SHETTY@GMAIL.COM    103

In [4]:
newdf.loc[2,['Name']]='Shishir'
newdf

NameError: name 'newdf' is not defined

In [15]:
#to find the length of all the rows of 'Email' column.
newdf['Email'].apply(len)

0    23
1    14
2    16
Name: Email, dtype: int64

In [18]:
#Another method to convert into Upper or lower
#Create a function 'Upper_Email' which takes one argument and converts into upper
def Upper_Email(email):
    return email.upper()
#pass the Function like below.It will convert all the rows in'Email'column to upper.
newdf['Email'] = newdf['Email'].apply(Upper_Email)

In [9]:
#Another method to convert into Upper or lower using Lambda method
newdf['Email']=newdf['Email'].apply(lambda x:x.lower())

            Name                    Email  Phone
0  shishirshetty  shishirshetty@gmail.com    100
1           Shir           shir@gmail.com    101
2           Shir         shetty@gmail.com    102

In [7]:
newdf

                     Email           Name  Phone
0  shishirshetty@gmail.com  shishirshetty    100
1           Shir@gmail.com           Shir    101
2         Shetty@gmail.com           Shir    102

In [19]:
#Instead of using loc or iloc we can make use of simple '.' indicator
Score={
    'Name': ['Hardik','Krunal','Pollard'],
    'Runs': [20,15,45],
    'Ball': [15,13,20]
}
import pandas as pd
df = pd.DataFrame(Score)
df[(df.Name == 'Pollard')].Runs

2    45
Name: Runs, dtype: int64

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

path="C:\\Users\\SHETTS60\\Documents\\Python scripts\\Cricket analytics Materials\\MSD Analysis\\ipl_ball_by_ball_data.csv"
df = pd.read_csv(path)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', -1)

In [2]:
df = df[(df['innings'] == 1) | (df['innings'] == 2)]

In [3]:
req_df = df[(df['striker'] == "AB de Villiers")]

In [8]:
tempdf = pd.DataFrame(req_df["bowler"].unique())

In [9]:
tempdf

                     0
0    MS Gony
1    M Ntini
2    M Muralitharan
3    JA Morkel
4    Joginder Sharma
5    SM Pollock
6    DJ Bravo
7    A Nehra
8    AD Mascarenhas
9    SK Trivedi
10   SK Warne
11   Shoaib Akhtar
12   I Sharma
13   AB Dinda
14   JH Kallis
15   B Akhil
16   A Kumble
17   DW Steyn
18   A Flintoff
19   L Balaji
20   KP Appanna
21   Pankaj Singh
22   MM Patel
23   Kamran Khan
24   YK Pathan
25   RA Jadeja
26   Shoaib Ahmed
27   RP Singh
28   S Tyagi
29   SL Malinga
30   JP Duminy
31   SR Tendulkar
32   RR Raje
33   Harbhajan Singh
34   MC Henriques
35   M Kartik
36   AB Agarkar
37   SS Sarkar
38   A Symonds
39   PP Ojha
40   DR Smith
41   WPUJC Vaas
42   PP Chawla
43   S Sreesanth
44   RR Powar
45   IK Pathan
46   AS Raut
47   J Botha
48   A Singh
49   RE van der Merwe
50   P Kumar
51   RG Sharma
52   Harmeet Singh
53   YA Abdulla
54   SW Tait
55   A Uniyal
56   KA Pollard
57   R Ashwin
58   R Sharma
59   R Vinay Kumar
60   AG Murtaza
61   RV Gomez
62   JEC Franklin
63   S Randiv
64   SB Jakati
65   SK Raina
66   TG Southee
67   UT Yadav
68   JD Ryder
69   Yuvraj Singh
70   AC Thomas
71   L Ablish
72   RJ Harris
73   R McLaren
74   Iqbal Abdulla
75   JD Unadkat
76   SJ Srivastava
77   PC Valthaty
78   AN Ahmed
79   DE Bollinger
80   DAJ Bracewell
81   S Nadeem
82   GJ Maxwell
83   M Morkel
84   R Bhatia
85   B Lee
86   GB Hogg
87   B Kumar
88   AD Mathews
89   P Awana
90   Azhar Mahmood
91   KK Cooper
92   A Chandila
93   DJ Hussey
94   Anand Rajan
95   A Ashish Reddy
96   V Pratap Singh
97   A Mishra
98   NLTC Perera
99   CL White
100  PJ Sangwan
101  SP Narine
102  DP Nannes
103  CH Morris
104  JP Faulkner
105  SR Watson
106  MR Marsh
107  DS Kulkarni
108  STR Binny
109  BAW Mendis
110  MG Neser
111  S Kaul
112  SMSM Senanayake
113  MM Sharma
114  Z Khan
115  JJ Bumrah
116  KW Richardson
117  Sandeep Sharma
118  MG Johnson
119  AR Patel
120  R Dhawan
121  KV Sharma
122  DJG Sammy
123  Shivam Sharma
124  PV Tambe
125  R Tewatia
126  Mohammed Shami
127  Imran Tahir
128  Parvez Rasool
129  Shakib Al Hasan
130  S Badree
131  KC Cariappa
132  AD Russell
133  TA Boult
134  RS Bopara
135  MJ McClenaghan
136  HH Pandya
137  IC Pandey
138  DJ Hooda
139  Anureet Singh
140  Karanveer Singh
141  J Suchith
142  Ankit Sharma
143  Mustafizur Rahman
144  CR Brathwaite
145  P Negi
146  KH Pandya
147  M Ashwin
148  BB Sran
149  A Zampa
150  MP Stoinis
151  S Kaushik
152  AS Rajpoot
153  KJ Abbott
154  Bipul Sharma
155  VR Aaron
156  T Natarajan
157  DT Christian
158  SN Thakur
159  BA Stokes
160  NM Coulter-Nile
161  AJ Tye
162  Ankit Soni
163  Basil Thampi
164  LH Ferguson
165  DL Chahar
166  CR Woakes
167  N Rana
168  Kuldeep Yadav
169  Mujeeb Ur Rahman
170  S Gopal
171  B Laughlin
172  HV Patel
173  Rashid Khan
174  S Lamichhane
175  CJ Dala
176  IS Sodhi
177  JC Archer
178  K Gowtham
179  M Markande
180  Mohammad Nabi
181  M Prasidh Krishna
182  K Rabada
183  SM Curran
184  RD Chahar
185  JP Behrendorff
186  GC Viljoen
187  SE Rutherford
188  KK Ahmed
189  Abhishek Sharma
190  SS Cottrell
191  Ravi Bishnoi
192  JL Pattinson
193  TK Curran
194  A Nortje
195  PJ Cummins
196  KL Nagarkoti
197  CV Varun
198  Kartik Tyagi
199  MJ Santner
200  Monu Kumar
201  DR Sams
202  JO Holder
203  M Jansen
204  Avesh Khan
205  Harpreet Brar

In [10]:
tempdf.to_csv('ABD_Bowlers.csv', index = False)

In [11]:
# to convert into dataframes
import pandas as pd

# extract url response/info
from urllib.request import urlopen

# to work with html content
from bs4 import BeautifulSoup

In [12]:
# find pages count, using page 1 as reference
url = "https://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;page=" + str(1) + ";template=results;type=bowling;view=innings"
text = urlopen(url)
soup = BeautifulSoup(text, "lxml")
table = soup.findAll('table', attrs = {'class' : 'engineTable'})

tr_list = table[1].findAll('tr', attrs = {'class': 'data2'})

min_pages = int(tr_list[0].findAll('b')[0].get_text())
max_pages = int(tr_list[0].findAll('b')[1].get_text())

entries_per_page = int(tr_list[0].findAll('b')[3].get_text())
total_players_count = int(tr_list[0].findAll('b')[4].get_text())

# set limits to run the for loop
min_limit = min_pages
if (total_players_count//entries_per_page) > 0:
    max_limit = max_pages + 1

# initialize all players data
all_players = []

for k in range(min_limit, max_limit):
    # url to text & then to soup object conversion
    url = "https://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;page=" + str(k) + ";template=results;type=bowling;view=innings"
    text = urlopen(url)
    soup = BeautifulSoup(text, "lxml")
    table = soup.findAll('table', attrs = {'class' : 'engineTable'})
    int_table = table[0]
    
    # iterate through all tables, find the one with caption tag
    for temp_table in table:
        caption_tag = temp_table.findAll('caption')
        if(len(caption_tag) > 0):
            int_table = temp_table
    
    # fetch table with data
    tr_list = int_table.findAll('tr', attrs = {'class': 'data1'})
    
    # populate data
    for tr in tr_list:
        td_list = tr.findAll('td')
        row_data = []
        for td in td_list:
            td_str = str(td)
            cleantext = BeautifulSoup(td_str, "lxml").get_text()
            row_data.append(cleantext)
        all_players.append(row_data)
        
    # populate column names
    tr_list_columns = int_table.findAll('tr', attrs = {'class': 'headlinks'})
    cols_count = len(tr_list_columns[0].findAll('th'))
    
    column_names_ls = []
    for i in range(cols_count):
        column_name = tr_list_columns[0].findAll('th')[i].get_text()
        column_names_ls.append(column_name)
        
    # convert to dataframe
    odi_bowl_ing_df = pd.DataFrame(all_players, columns = column_names_ls)

KeyboardInterrupt:

In [ ]:
len(odi_bowl_ing_df)

In [13]:
odi_bowl_ing_df.to_csv('ABD_Bowlers.csv', index = False)